version: '3.8'

services:

  website:
    restart: unless-stopped
    image: ghcr.io/alecks20/alecks.dev:latest
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./db:/data/db
    env_file:
      - .env
    #ports:
    #  - "5050:27017"

  #api:
  #  restart: unless-stopped
  #  image: ghcr.io/alecks20/api:latest
  #  env_file:
  #   - .env

  proxy:
    image: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
      
