version: '3.8'

services:

  website:
    restart: unless-stopped
    image: ghcr.io/alecks20/alecks.dev:latest
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./db:/data/db
    env_file:
      - .env

  proxy:
    image: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

  packs:
    image: ghcr.io/alecks20/packs-website:latest
    restart: unless-stopped
    volumes:
      - ./cdn/packs:/packs
    depends_on:
      - db
    env_file:
      - .env

  #activating when cdn is done
  #cdn:
  #  image: ghcr.io/alecks20/cdn:latest
  #  restart: unless-stopped
  #  volumes:
  #    - ./cdn:/content
  #  env_file:
  #    - .env

  #rclone:
  #  restart: unless-stopped
  #  image: rclone/rclone:latest
  #  command: ["sync", "/data", "b2:alecks-backups/alecks-dev-db", "--progress"]
  #  volumes:
  #    - ./rclone.conf:/config/rclone/rclone.conf:ro
  #    - ./db:/data:ro
  #  environment:
  #    - RCLONE_CONFIG=/config/rclone/rclone.conf


